[project]
name = "da-agent"
version = "0.1.0"
requires-python = "==3.11"
dependencies = [
  "fastapi>=0.116,<1",
  "langgraph>=0.6.4,<1",
]

[project.optional-dependencies]
dev = [
  "pytest>=8,<9",
  "pylint>=3.3.8,<4",
]
